### ISSUE TITLE
Fehler Update Version 0.6.0 zu 1.0.0

### ISSUE THREAD

**Issue by Hypnos3** [ioBroker/ioBroker.mihome-vacuum#39]
Fehler Update Version 0.6.0 zu 1.1.0:
```
$ ./iobroker upgrade mihome-vacuum
Update mihome-vacuum from @0.6.0 to @1.1.0
NPM version: 3.10.10
npm install iobroker.mihome-vacuum@1.1.0 --production --save --prefix "/opt/iobroker" (System call)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/iobroker.js2fs/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm install --production (System call) in "/opt/iobroker/node_modules/iobroker.mihome-vacuum"
got /opt/iobroker/node_modules/iobroker.mihome-vacuum/admin
upload [4] mihome-vacuum.admin /opt/iobroker/node_modules/iobroker.mihome-vacuum/admin/words.js words.js application/javascript
ERROR: /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:431                    target[attr] = additional[attr];
                                 ^

TypeError: Cannot create property 'en' on string 'This adapter allows control Xiaomi vacuum cleaner'
    at extendCommon (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:431:34)
    at extendCommon (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:434:21)
    at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:487:64)
    at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
    at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
    at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
    at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
    at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
    at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)

ERROR: process exited with code 1
```

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.js-controller/commit/3bf3ac1430abf5cec6cf9d4e4983c474eeb20477

2018-04-11 22:32 GMT+02:00 Robert <notifications@github.com>:

**Comment by Apollon77** [comment]
Zu erklärung: liegt am 1.4.0 js-controller.

**Comment by kueppert** [comment]
Geht um Update auf v1.10 Anbei mein Fehler Code:

$ ./iobroker upgrade mihome-vacuum
Update mihome-vacuum from @0.6.0 to @1.1.0
NPM version: 5.7.1
npm install iobroker.mihome-vacuum@1.1.0 --production --save --prefix "/opt/iobroker" (System call)
npm install --production (System call) in "/opt/iobroker/node_modules/iobroker.mihome-vacuum"
npm
notice created a lockfile as package-lock.json. You should commit this file.
got /opt/iobroker/node_modules/iobroker.mihome-vacuum/admin
upload [4] mihome-vacuum.admin /opt/iobroker/node_modules/iobroker.mihome-vacuum/admin/words.js words.js application/javascript
ERROR: /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:431 target[attr] = additional[attr];
^

TypeError: Cannot create property 'en' on string 'This adapter allows control Xiaomi vacuum cleaner'
at extendCommon (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:431:34)
at extendCommon (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:434:21)
at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:487:64)
at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:312:9)
at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
at Manager.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-bind/index.js:21:15)
at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:332:8)
at Decoder.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-bind/index.js:21:15)
at Decoder.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:134:20)

ERROR: process exited with code 1

VG Thorsten

**Comment by Apollon77** [comment]
Welche Version des js-Controller Ist installiert?

**Comment by kueppert** [comment]
V1.4.0

**Comment by robdg80** [comment]
OK, ich habe jetzt ein Update von V1.4.0 auf V1.4.2 eingespielt.

Jetzt startet der Adapter ständig neu mit folgendem Fehler:

`host.GD-Server | 2018-04-16 19:53:45.116 | info | instance system.adapter.mihome-vacuum.0 started with pid 37674
-- | -- | -- | --
host.GD-Server | 2018-04-16 19:53:15.100 | info | Restart adapter system.adapter.mihome-vacuum.0 because enabled
host.GD-Server | 2018-04-16 19:53:15.100 | error | instance system.adapter.mihome-vacuum.0 terminated with code 0 (OK)
Caught | 2018-04-16 19:53:15.100 | error | by controller[0]: at UDP.onMessage (dgram.js:561:8)
Caught | 2018-04-16 19:53:15.100 | error | by controller[0]: at Socket.emit (events.js:191:7)
Caught | 2018-04-16 19:53:15.100 | error | by controller[0]: at emitTwo (events.js:106:13)
Caught | 2018-04-16 19:53:15.100 | error | by controller[0]: at Socket. (/opt/iobroker/node_modules/iobroker.mihome-vacuum/main.js:840:21)
Caught | 2018-04-16 19:53:15.100 | error | by controller[0]: at getStates (/opt/iobroker/node_modules/iobroker.mihome-vacuum/main.js:411:23)
Caught | 2018-04-16 19:53:15.099 | error | by controller[0]: at Object.parse (native)
Caught | 2018-04-16 19:53:15.099 | error | by controller[0]: SyntaxError: Unexpected end of JSON input
mihome-vacuum.0 | 2018-04-16 19:53:15.088 | info | terminating
mihome-vacuum.0 | 2018-04-16 19:53:15.085 | error | at UDP.onMessage (dgram.js:561:8)
mihome-vacuum.0 | 2018-04-16 19:53:15.085 | error | at Socket.emit (events.js:191:7)
mihome-vacuum.0 | 2018-04-16 19:53:15.085 | error | at emitTwo (events.js:106:13)
mihome-vacuum.0 | 2018-04-16 19:53:15.085 | error | at Socket. (/opt/iobroker/node_modules/iobroker.mihome-vacuum/main.js:840:21)
mihome-vacuum.0 | 2018-04-16 19:53:15.085 | error | at getStates (/opt/iobroker/node_modules/iobroker.mihome-vacuum/main.js:411:23)
mihome-vacuum.0 | 2018-04-16 19:53:15.085 | error | at Object.parse (native)
mihome-vacuum.0 | 2018-04-16 19:53:15.085 | error | SyntaxError: Unexpected end of JSON input
mihome-vacuum.0 | 2018-04-16 19:53:15.084 | error | uncaught exception: Unexpected end of JSON input
mihome-vacuum.0 | 2018-04-16 19:53:14.867 | warn | Time difference between Mihome Vacuum and ioBroker: -1523840534 sec
mihome-vacuum.0 | 2018-04-16 19:53:14.840 | info | Cloud control disabled
mihome-vacuum.0 | 2018-04-16 19:53:14.839 | info | Expert mode enabled, states created
mihome-vacuum.0 | 2018-04-16 19:53:14.834 | info | starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.mihome-vacuum, node: v6.14.1
mihome-vacuum.0 | 2018-04-16 19:53:14.669 | info | States connected to redis: 127.0.0.1:6379
host.GD-Server | 2018-04-16 19:53:14.222 | info | instance system.adapter.mihome-vacuum.0 started with pid 37658
host.GD-Server | 2018-04-16 19:52:44.206 | info | Restart adapter system.adapter.mihome-vacuum.0 because enabled`

**Comment by MeisterTR** [comment]
Dein Sauger hat kein Internet oder? Ich kümmere mich drum, dass der Fehler abgefangen wird. Jodoch solltest du das Internet freischalten für den Sauger. In den neueren sw   Versionen des saugers arbeitet die lokale Kommunikation nur, wenn der Sauger einen Internet Zugang hat.

**Comment by robdg80** [comment]
Ja, ich habe Internet gesperrt.

Das mit den neuen Versionen die Lokale Kommunikation ohne Internet nicht funktioniert kann ich aber nicht bestätigen. Das funktionierte mit dem Adapter mit der Version V1.4.0 problemlos.
