### ISSUE TITLE
Syntax Fehler bei ?

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.mihome-vacuum#40]
Bei Internetausfall?

```
2018-04-13 17:08:40.201 - error: Caught by controller[0]: SyntaxError: Unexpected end of JSON input
--
2018-04-13 17:08:40.201 - error: Caught by controller[0]: at JSON.parse ()
2018-04-13 17:08:40.201 - error: Caught by controller[0]: at getStates (/opt/iobroker/node_modules/iobroker.mihome-vacuum/main.js:411:23)
2018-04-13 17:08:40.201 - error: Caught by controller[0]: at Socket. (/opt/iobroker/node_modules/iobroker.mihome-vacuum/main.js:840:21)
2018-04-13 17:08:40.201 - error: Caught by controller[0]: at emitTwo (events.js:126:13)
2018-04-13 17:08:40.201 - error: Caught by controller[0]: at Socket.emit (events.js:214:7)
2018-04-13 17:08:40.201 - error: Caught by controller[0]: at UDP.onMessage [as onmessage] (dgram.js:659:8)
2018-04-13 17:08:40.201 - error: host.iobrokerng2 instance system.adapter.mihome-vacuum.0 terminated with code 0 (OK)
```

**Comment by MeisterTR** [comment]
Den Fehler beseitige ich, dass ändern jedoch nix daran, dass der Sauger ohne Internet nicht mehr ordnungsgemäß Daten liefert. Das hat xiaomi in den neueren sw Versionen mit eingebaut..
