### ISSUE TITLE
Fehler im Adapter 

### ISSUE THREAD

**Issue by Blackei** [ioBroker/ioBroker.mihome-vacuum#47]
Hallo zusammen,
habe ein Problem mit dem Adapter. Der Token passt und die IP auch. Es scheint als würde der Adapter immer die Verbindung verlieren:

`

host.iobroker | 2018-08-12 10:30:21.227 | error | instance system.adapter.mihome-vacuum.0 terminated with code 0 (OK)
-- | -- | -- | --
host.iobroker | 2018-08-12 10:30:21.227 | error | Caught by controller[1]: at process._tickCallback (internal/process/next_tick.js:180:9)
host.iobroker | 2018-08-12 10:30:21.227 | error | Caught by controller[1]: at _combinedTickCallback (internal/process/next_tick.js:131:7)
host.iobroker | 2018-08-12 10:30:21.227 | error | Caught by controller[1]: at processImmediate (timers.js:729:5)
host.iobroker | 2018-08-12 10:30:21.226 | error | Caught by controller[1]: at tryOnImmediate (timers.js:752:5)
host.iobroker | 2018-08-12 10:30:21.226 | error | Caught by controller[1]: at runCallback (timers.js:794:20)
host.iobroker | 2018-08-12 10:30:21.226 | error | Caught by controller[1]: at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3712:38)
host.iobroker | 2018-08-12 10:30:21.226 | error | Caught by controller[1]: at Adapter.emit (events.js:214:7)
host.iobroker | 2018-08-12 10:30:21.226 | error | Caught by controller[1]: at emitTwo (events.js:126:13)
host.iobroker | 2018-08-12 10:30:21.226 | error | Caught by controller[1]: at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.mihome-vacuum/main.js:124:13)
host.iobroker | 2018-08-12 10:30:21.226 | error | Caught by controller[1]: at parseGoTo (/opt/iobroker/node_modules/iobroker.mihome-vacuum/main.js:196:30)
host.iobroker | 2018-08-12 10:30:21.226 | error | Caught by controller[1]: TypeError: Cannot read property 'split' of undefined
host.iobroker | 2018-08-12 10:30:21.226 | error | Caught by controller[0]: at processImmediate [as _immediateCallback] (timers.js:729:5)
host.iobroker | 2018-08-12 10:30:21.226 | error | Caught by controller[0]: at tryOnImmediate (timers.js:752:5)
host.iobroker | 2018-08-12 10:30:21.226 | error | Caught by controller[0]: at runCallback (timers.js:794:20)
host.iobroker | 2018-08-12 10:30:21.225 | error | Caught by controller[0]: at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3712:38)
host.iobroker | 2018-08-12 10:30:21.225 | error | Caught by controller[0]: at Adapter.emit (events.js:214:7)
host.iobroker | 2018-08-12 10:30:21.225 | error | Caught by controller[0]: at emitTwo (events.js:126:13)
host.iobroker | 2018-08-12 10:30:21.225 | error | Caught by controller[0]: at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.mihome-vacuum/main.js:81:36)
host.iobroker | 2018-08-12 10:30:21.225 | error | Caught by controller[0]: TypeError: Cannot read property 'trim' of undefined

`

**Comment by MeisterTR** [comment]
kannsz du den adapter mal bitte auf debug stellen und erneut einen logauszug posten

**Comment by GermanBluefox** [comment]
@Blackei Du schicks irgendwas falsches.
Probiere die Version vom git
